openapi: 3.0.0
info:
  version: 2015-10-01
  x-release: v4
  title: 'Amazon GameLift #X Amz Target=GameLift.AcceptMatch #X Amz Target=GameLift.AcceptMatch #X Amz Target=GameLift.RegisterCompute API'
  description: <p>Amazon GameLift provides solutions for hosting session-based multiplayer game servers in the cloud, including tools for deploying, operating, and scaling game servers. Built on Amazon Web Services global computing infrastructure, GameLift helps you deliver high-performance, high-reliability, low-cost game servers while dynamically scaling your resource usage to meet player demand. </p> <p> <b>About Amazon GameLift solutions</b> </p> <p>Get more information on these Amazon GameLift solutions in the <a href="https://docs.aws.amazon.com/gamelift/latest/developerguide/">Amazon GameLift Developer Guide</a>.</p> <ul> <li> <p>Amazon GameLift managed hosting -- Amazon GameLift offers a fully managed service to set up and maintain computing machines for hosting, manage game session and player session life cycle, and handle security, storage, and performance tracking. You can use automatic scaling tools to balance player demand and hosting costs, configure your game session management to minimize player latency, and add FlexMatch for matchmaking.</p> </li> <li> <p>Managed hosting with Realtime Servers -- With Amazon GameLift Realtime Servers, you can quickly configure and set up ready-to-go game servers for your game. Realtime Servers provides a game server framework with core Amazon GameLift infrastructure already built in. Then use the full range of Amazon GameLift managed hosting features, including FlexMatch, for your game.</p> </li> <li> <p>Amazon GameLift FleetIQ -- Use Amazon GameLift FleetIQ as a standalone service while hosting your games using EC2 instances and Auto Scaling groups. Amazon GameLift FleetIQ provides optimizations for game hosting, including boosting the viability of low-cost Spot Instances gaming. For a complete solution, pair the Amazon GameLift FleetIQ and FlexMatch standalone services.</p> </li> <li> <p>Amazon GameLift FlexMatch -- Add matchmaking to your game hosting solution. FlexMatch is a customizable matchmaking service for multiplayer games. Use FlexMatch as integrated with Amazon GameLift managed hosting or incorporate FlexMatch as a standalone service into your own hosting solution.</p> </li> </ul> <p> <b>About this API Reference</b> </p> <p>This reference guide describes the low-level service API for Amazon GameLift. With each topic in this guide, you can find links to language-specific SDK guides and the Amazon Web Services CLI reference. Useful links:</p> <ul> <li> <p> <a href="https://docs.aws.amazon.com/gamelift/latest/developerguide/reference-awssdk.html">Amazon GameLift API operations listed by tasks</a> </p> </li> <li> <p> <a href="https://docs.aws.amazon.com/gamelift/latest/developerguide/gamelift-components.html"> Amazon GameLift tools and resources</a> </p> </li> </ul>
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: gamelift
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/gamelift-2015-10-01.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://gamelift.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon GameLift multi-region endpoint
- url: https://gamelift.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon GameLift multi-region endpoint
- url: http://gamelift.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon GameLift endpoint for China (Beijing) and China (Ningxia)
- url: https://gamelift.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon GameLift endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: '#X Amz Target=GameLift.RegisterCompute'
paths:
  /#X-Amz-Target=GameLift.RegisterCompute:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    post:
      operationId: RegisterCompute
      description: <p>Registers your compute resources in a fleet you previously created. After you register a compute to your fleet, you can monitor and manage your compute using Amazon GameLift. The operation returns the compute resource containing SDK endpoint you can use to connect your game server to Amazon GameLift.</p> <p> <b>Learn more</b> </p> <ul> <li> <p> <a href="https://docs.aws.amazon.com/gamelift/latest/developerguide/fleets-creating-anywhere.html">Create an Anywhere fleet</a> </p> </li> <li> <p> <a href="https://docs.aws.amazon.com/gamelift/latest/developerguide/integration-testing.html">Test your integration</a> </p> </li> </ul>
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegisterComputeOutput'
              examples:
                RegisterCompute200Example:
                  summary: Default RegisterCompute 200 response
                  x-microcks-default: true
                  value:
                    Compute: example-value
        '480':
          description: UnauthorizedException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnauthorizedException'
              examples:
                RegisterCompute480Example:
                  summary: Default RegisterCompute 480 response
                  x-microcks-default: true
                  value: example-value
        '481':
          description: InvalidRequestException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidRequestException'
              examples:
                RegisterCompute481Example:
                  summary: Default RegisterCompute 481 response
                  x-microcks-default: true
                  value: example-value
        '482':
          description: ConflictException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConflictException'
              examples:
                RegisterCompute482Example:
                  summary: Default RegisterCompute 482 response
                  x-microcks-default: true
                  value: example-value
        '483':
          description: InternalServiceException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServiceException'
              examples:
                RegisterCompute483Example:
                  summary: Default RegisterCompute 483 response
                  x-microcks-default: true
                  value: example-value
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterComputeInput'
      parameters:
      - name: X-Amz-Target
        in: header
        required: true
        schema:
          type: string
          enum:
          - GameLift.RegisterCompute
      summary: Amazon GameLift Register Compute
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - '#X Amz Target=GameLift.RegisterCompute'
components:
  schemas:
    ConflictException: {}
    RegisterComputeOutput:
      type: object
      properties:
        Compute:
          allOf:
          - $ref: '#/components/schemas/Compute'
          - description: The details of the compute resource you registered to the specified fleet.
    ComputeArn:
      type: string
      pattern: ^arn:.*:compute\/[a-zA-Z0-9\-]+
      maxLength: 1024
    NonZeroAndMaxString:
      type: string
      minLength: 1
      maxLength: 1024
    FleetId:
      type: string
      pattern: ^fleet-\S+
    InternalServiceException: {}
    FleetArn:
      type: string
      pattern: ^arn:.*:fleet\/fleet-\S+
    RegisterComputeInput:
      type: object
      required:
      - FleetId
      - ComputeName
      title: RegisterComputeInput
      properties:
        FleetId:
          allOf:
          - $ref: '#/components/schemas/FleetIdOrArn'
          - description: A unique identifier for the fleet to register the compute to. You can use either the fleet ID or ARN value.
        ComputeName:
          allOf:
          - $ref: '#/components/schemas/ComputeName'
          - description: A descriptive label that is associated with the compute resource registered to your fleet.
        CertificatePath:
          allOf:
          - $ref: '#/components/schemas/NonZeroAndMaxString'
          - description: The path to the TLS certificate on your compute resource. The path and certificate are not validated by Amazon GameLift.
        DnsName:
          allOf:
          - $ref: '#/components/schemas/DnsNameInput'
          - description: The DNS name of the compute resource. Amazon GameLift requires the DNS name or IP address to manage your compute resource.
        IpAddress:
          allOf:
          - $ref: '#/components/schemas/IpAddress'
          - description: The IP address of the compute resource. Amazon GameLift requires the DNS name or IP address to manage your compute resource.
        Location:
          allOf:
          - $ref: '#/components/schemas/LocationStringModel'
          - description: The name of the custom location you added to the fleet you are registering this compute resource to.
    IpAddress:
      type: string
      pattern: ^[0-9A-Fa-f\:\.]+
      minLength: 1
      maxLength: 128
    ComputeName:
      type: string
      pattern: ^[a-zA-Z0-9\-]+
      minLength: 1
      maxLength: 128
    FleetIdOrArn:
      type: string
      pattern: ^fleet-\S+|^arn:.*:fleet\/fleet-\S+
    ComputeStatus:
      type: string
      enum:
      - PENDING
      - ACTIVE
      - TERMINATING
    DnsNameInput:
      type: string
      pattern: ^[0-9a-zA-Z_\-\.]+
      minLength: 1
      maxLength: 256
    GameLiftServiceSdkEndpointOutput:
      type: string
      minLength: 1
      maxLength: 128
    InvalidRequestException: {}
    DnsName:
      type: string
    EC2InstanceType:
      type: string
      enum:
      - t2.micro
      - t2.small
      - t2.medium
      - t2.large
      - c3.large
      - c3.xlarge
      - c3.2xlarge
      - c3.4xlarge
      - c3.8xlarge
      - c4.large
      - c4.xlarge
      - c4.2xlarge
      - c4.4xlarge
      - c4.8xlarge
      - c5.large
      - c5.xlarge
      - c5.2xlarge
      - c5.4xlarge
      - c5.9xlarge
      - c5.12xlarge
      - c5.18xlarge
      - c5.24xlarge
      - c5a.large
      - c5a.xlarge
      - c5a.2xlarge
      - c5a.4xlarge
      - c5a.8xlarge
      - c5a.12xlarge
      - c5a.16xlarge
      - c5a.24xlarge
      - r3.large
      - r3.xlarge
      - r3.2xlarge
      - r3.4xlarge
      - r3.8xlarge
      - r4.large
      - r4.xlarge
      - r4.2xlarge
      - r4.4xlarge
      - r4.8xlarge
      - r4.16xlarge
      - r5.large
      - r5.xlarge
      - r5.2xlarge
      - r5.4xlarge
      - r5.8xlarge
      - r5.12xlarge
      - r5.16xlarge
      - r5.24xlarge
      - r5a.large
      - r5a.xlarge
      - r5a.2xlarge
      - r5a.4xlarge
      - r5a.8xlarge
      - r5a.12xlarge
      - r5a.16xlarge
      - r5a.24xlarge
      - m3.medium
      - m3.large
      - m3.xlarge
      - m3.2xlarge
      - m4.large
      - m4.xlarge
      - m4.2xlarge
      - m4.4xlarge
      - m4.10xlarge
      - m5.large
      - m5.xlarge
      - m5.2xlarge
      - m5.4xlarge
      - m5.8xlarge
      - m5.12xlarge
      - m5.16xlarge
      - m5.24xlarge
      - m5a.large
      - m5a.xlarge
      - m5a.2xlarge
      - m5a.4xlarge
      - m5a.8xlarge
      - m5a.12xlarge
      - m5a.16xlarge
      - m5a.24xlarge
      - c5d.large
      - c5d.xlarge
      - c5d.2xlarge
      - c5d.4xlarge
      - c5d.9xlarge
      - c5d.12xlarge
      - c5d.18xlarge
      - c5d.24xlarge
      - c6a.large
      - c6a.xlarge
      - c6a.2xlarge
      - c6a.4xlarge
      - c6a.8xlarge
      - c6a.12xlarge
      - c6a.16xlarge
      - c6a.24xlarge
      - c6i.large
      - c6i.xlarge
      - c6i.2xlarge
      - c6i.4xlarge
      - c6i.8xlarge
      - c6i.12xlarge
      - c6i.16xlarge
      - c6i.24xlarge
      - r5d.large
      - r5d.xlarge
      - r5d.2xlarge
      - r5d.4xlarge
      - r5d.8xlarge
      - r5d.12xlarge
      - r5d.16xlarge
      - r5d.24xlarge
    UnauthorizedException: {}
    Timestamp:
      type: string
      format: date-time
    LocationStringModel:
      type: string
      pattern: ^[A-Za-z0-9\-]+
      minLength: 1
      maxLength: 64
    OperatingSystem:
      type: string
      enum:
      - WINDOWS_2012
      - AMAZON_LINUX
      - AMAZON_LINUX_2
      - WINDOWS_2016
    Compute:
      type: object
      properties:
        FleetId:
          allOf:
          - $ref: '#/components/schemas/FleetId'
          - description: A unique identifier for the fleet that the compute is registered to.
        FleetArn:
          allOf:
          - $ref: '#/components/schemas/FleetArn'
          - description: The Amazon Resource Name (ARN) of the fleet that the compute is registered to.
        ComputeName:
          allOf:
          - $ref: '#/components/schemas/ComputeName'
          - description: A descriptive label that is associated with the compute resource registered to your fleet.
        ComputeArn:
          allOf:
          - $ref: '#/components/schemas/ComputeArn'
          - description: The ARN that is assigned to the compute resource and uniquely identifies it. ARNs are unique across locations.
        IpAddress:
          allOf:
          - $ref: '#/components/schemas/IpAddress'
          - description: The IP address of the compute resource. Amazon GameLift requires the DNS name or IP address to manage your compute resource.
        DnsName:
          allOf:
          - $ref: '#/components/schemas/DnsName'
          - description: The DNS name of the compute resource. Amazon GameLift requires the DNS name or IP address to manage your compute resource.
        ComputeStatus:
          allOf:
          - $ref: '#/components/schemas/ComputeStatus'
          - description: Current status of the compute. A compute must have an <code>ACTIVE</code> status to host game sessions.
        Location:
          allOf:
          - $ref: '#/components/schemas/LocationStringModel'
          - description: The name of the custom location you added to the fleet that this compute resource resides in.
        CreationTime:
          allOf:
          - $ref: '#/components/schemas/Timestamp'
          - description: A time stamp indicating when this data object was created. Format is a number expressed in Unix time as milliseconds (for example <code>"1469498468.057"</code>).
        OperatingSystem:
          allOf:
          - $ref: '#/components/schemas/OperatingSystem'
          - description: The type of operating system on your compute resource.
        Type:
          allOf:
          - $ref: '#/components/schemas/EC2InstanceType'
          - description: The compute type that the fleet uses. A fleet can use Anywhere compute resources that you own, or use managed Amazon EC2 instances.
        GameLiftServiceSdkEndpoint:
          allOf:
          - $ref: '#/components/schemas/GameLiftServiceSdkEndpointOutput'
          - description: The endpoint connection details of the Amazon GameLift SDK endpoint that your game server connects to.
      description: Resources used to host your game servers. A compute resource can be managed Amazon GameLift Amazon EC2 instances or your own resources.
  parameters:
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/gamelift/
x-hasEquivalentPaths: true
