openapi: 3.0.0
info:
  version: "1.0.0"
  x-release: v4
  title: 'Amazon GameLift #X Amz Target=GameLift.AcceptMatch #X Amz Target=GameLift.AcceptMatch #X Amz Target=GameLift.ListGameServers API'
  description: <p>Amazon GameLift provides solutions for hosting session-based multiplayer game servers in the cloud, including tools for deploying, operating, and scaling game servers. Built on Amazon Web Services global computing infrastructure, GameLift helps you deliver high-performance, high-reliability, low-cost game servers while dynamically scaling your resource usage to meet player demand. </p> <p> <b>About Amazon GameLift solutions</b> </p> <p>Get more information on these Amazon GameLift solutions in the <a href="https://docs.aws.amazon.com/gamelift/latest/developerguide/">Amazon GameLift Developer Guide</a>.</p> <ul> <li> <p>Amazon GameLift managed hosting -- Amazon GameLift offers a fully managed service to set up and maintain computing machines for hosting, manage game session and player session life cycle, and handle security, storage, and performance tracking. You can use automatic scaling tools to balance player demand and hosting costs, configure your game session management to minimize player latency, and add FlexMatch for matchmaking.</p> </li> <li> <p>Managed hosting with Realtime Servers -- With Amazon GameLift Realtime Servers, you can quickly configure and set up ready-to-go game servers for your game. Realtime Servers provides a game server framework with core Amazon GameLift infrastructure already built in. Then use the full range of Amazon GameLift managed hosting features, including FlexMatch, for your game.</p> </li> <li> <p>Amazon GameLift FleetIQ -- Use Amazon GameLift FleetIQ as a standalone service while hosting your games using EC2 instances and Auto Scaling groups. Amazon GameLift FleetIQ provides optimizations for game hosting, including boosting the viability of low-cost Spot Instances gaming. For a complete solution, pair the Amazon GameLift FleetIQ and FlexMatch standalone services.</p> </li> <li> <p>Amazon GameLift FlexMatch -- Add matchmaking to your game hosting solution. FlexMatch is a customizable matchmaking service for multiplayer games. Use FlexMatch as integrated with Amazon GameLift managed hosting or incorporate FlexMatch as a standalone service into your own hosting solution.</p> </li> </ul> <p> <b>About this API Reference</b> </p> <p>This reference guide describes the low-level service API for Amazon GameLift. With each topic in this guide, you can find links to language-specific SDK guides and the Amazon Web Services CLI reference. Useful links:</p> <ul> <li> <p> <a href="https://docs.aws.amazon.com/gamelift/latest/developerguide/reference-awssdk.html">Amazon GameLift API operations listed by tasks</a> </p> </li> <li> <p> <a href="https://docs.aws.amazon.com/gamelift/latest/developerguide/gamelift-components.html"> Amazon GameLift tools and resources</a> </p> </li> </ul>
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: gamelift
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/gamelift-2015-10-01.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://gamelift.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon GameLift multi-region endpoint
- url: https://gamelift.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon GameLift multi-region endpoint
- url: http://gamelift.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon GameLift endpoint for China (Beijing) and China (Ningxia)
- url: https://gamelift.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon GameLift endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: '#X Amz Target=GameLift.ListGameServers'
paths:
  /#X-Amz-Target=GameLift.ListGameServers:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    post:
      operationId: ListGameServers
      description: <p> <b>This operation is used with the Amazon GameLift FleetIQ solution and game server groups.</b> </p> <p>Retrieves information on all game servers that are currently active in a specified game server group. You can opt to sort the list by game server age. Use the pagination parameters to retrieve results in a set of sequential segments. </p> <p> <b>Learn more</b> </p> <p> <a href="https://docs.aws.amazon.com/gamelift/latest/fleetiqguide/gsg-intro.html">Amazon GameLift FleetIQ Guide</a> </p>
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListGameServersOutput'
              examples:
                ListGameServers200Example:
                  summary: Default ListGameServers 200 response
                  x-microcks-default: true
                  value:
                    GameServers: example-value
                    NextToken: example-value
        '480':
          description: InvalidRequestException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidRequestException'
              examples:
                ListGameServers480Example:
                  summary: Default ListGameServers 480 response
                  x-microcks-default: true
                  value: example-value
        '481':
          description: UnauthorizedException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnauthorizedException'
              examples:
                ListGameServers481Example:
                  summary: Default ListGameServers 481 response
                  x-microcks-default: true
                  value: example-value
        '482':
          description: InternalServiceException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServiceException'
              examples:
                ListGameServers482Example:
                  summary: Default ListGameServers 482 response
                  x-microcks-default: true
                  value: example-value
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ListGameServersInput'
      parameters:
      - name: Limit
        in: query
        schema:
          type: string
        description: Pagination limit
        required: false
      - name: NextToken
        in: query
        schema:
          type: string
        description: Pagination token
        required: false
      - name: X-Amz-Target
        in: header
        required: true
        schema:
          type: string
          enum:
          - GameLift.ListGameServers
      summary: Amazon GameLift List Game Servers
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - '#X Amz Target=GameLift.ListGameServers'
components:
  schemas:
    NonZeroAndMaxString:
      type: string
      minLength: 1
      maxLength: 1024
    GameServerGroupNameOrArn:
      type: string
      pattern: '[a-zA-Z0-9-\.]+|^arn:.*:gameservergroup\/[a-zA-Z0-9-\.]+'
      minLength: 1
      maxLength: 256
    InternalServiceException: {}
    GameServerGroupArn:
      type: string
      pattern: ^arn:.*:gameservergroup\/[a-zA-Z0-9-\.]*
      minLength: 1
      maxLength: 256
    ListGameServersOutput:
      type: object
      properties:
        GameServers:
          allOf:
          - $ref: '#/components/schemas/GameServers'
          - description: A collection of game server objects that match the request.
        NextToken:
          allOf:
          - $ref: '#/components/schemas/NonZeroAndMaxString'
          - description: A token that indicates where to resume retrieving results on the next call to this operation. If no token is returned, these results represent the end of the list.
    GameServerId:
      type: string
      pattern: '[a-zA-Z0-9-\.]+'
      minLength: 3
      maxLength: 128
    GameServerGroupName:
      type: string
      pattern: '[a-zA-Z0-9-\.]+'
      minLength: 1
      maxLength: 128
    GameServerClaimStatus:
      type: string
      enum:
      - CLAIMED
    GameServerInstanceId:
      type: string
      pattern: ^i-[0-9a-zA-Z]{17}$
      minLength: 19
      maxLength: 19
    GameServer:
      type: object
      properties:
        GameServerGroupName:
          allOf:
          - $ref: '#/components/schemas/GameServerGroupName'
          - description: A unique identifier for the game server group where the game server is running.
        GameServerGroupArn:
          allOf:
          - $ref: '#/components/schemas/GameServerGroupArn'
          - description: The ARN identifier for the game server group where the game server is located.
        GameServerId:
          allOf:
          - $ref: '#/components/schemas/GameServerId'
          - description: A custom string that uniquely identifies the game server. Game server IDs are developer-defined and are unique across all game server groups in an Amazon Web Services account.
        InstanceId:
          allOf:
          - $ref: '#/components/schemas/GameServerInstanceId'
          - description: 'The unique identifier for the instance where the game server is running. This ID is available in the instance metadata. EC2 instance IDs use a 17-character format, for example: <code>i-1234567890abcdef0</code>.'
        ConnectionInfo:
          allOf:
          - $ref: '#/components/schemas/GameServerConnectionInfo'
          - description: The port and IP address that must be used to establish a client connection to the game server.
        GameServerData:
          allOf:
          - $ref: '#/components/schemas/GameServerData'
          - description: A set of custom game server properties, formatted as a single string value. This data is passed to a game client or service when it requests information on game servers.
        ClaimStatus:
          allOf:
          - $ref: '#/components/schemas/GameServerClaimStatus'
          - description: Indicates when an available game server has been reserved for gameplay but has not yet started hosting a game. Once it is claimed, the game server remains in <code>CLAIMED</code> status for a maximum of one minute. During this time, game clients connect to the game server to start the game and trigger the game server to update its utilization status. After one minute, the game server claim status reverts to null.
        UtilizationStatus:
          allOf:
          - $ref: '#/components/schemas/GameServerUtilizationStatus'
          - description: <p>Indicates whether the game server is currently available for new games or is busy. Possible statuses include:</p> <ul> <li> <p> <code>AVAILABLE</code> - The game server is available to be claimed. A game server that has been claimed remains in this status until it reports game hosting activity. </p> </li> <li> <p> <code>UTILIZED</code> - The game server is currently hosting a game session with players. </p> </li> </ul>
        RegistrationTime:
          allOf:
          - $ref: '#/components/schemas/Timestamp'
          - description: Timestamp that indicates when the game server registered. The format is a number expressed in Unix time as milliseconds (for example <code>"1469498468.057"</code>).
        LastClaimTime:
          allOf:
          - $ref: '#/components/schemas/Timestamp'
          - description: Timestamp that indicates the last time the game server was claimed. The format is a number expressed in Unix time as milliseconds (for example <code>"1469498468.057"</code>). This value is used to calculate when a claimed game server's status should revert to null.
        LastHealthCheckTime:
          allOf:
          - $ref: '#/components/schemas/Timestamp'
          - description: Timestamp that indicates the last time the game server was updated with health status. The format is a number expressed in Unix time as milliseconds (for example <code>"1469498468.057"</code>). After game server registration, this property is only changed when a game server update specifies a health check value.
      description: <p> <b>This data type is used with the Amazon GameLift FleetIQ and game server groups.</b> </p> <p>Properties describing a game server that is running on an instance in a game server group. </p> <p>A game server is created by a successful call to <code>RegisterGameServer</code> and deleted by calling <code>DeregisterGameServer</code>. A game server is claimed to host a game session by calling <code>ClaimGameServer</code>. </p>
    InvalidRequestException: {}
    ListGameServersInput:
      type: object
      required:
      - GameServerGroupName
      title: ListGameServersInput
      properties:
        GameServerGroupName:
          allOf:
          - $ref: '#/components/schemas/GameServerGroupNameOrArn'
          - description: An identifier for the game server group to retrieve a list of game servers from. Use either the name or ARN value.
        SortOrder:
          allOf:
          - $ref: '#/components/schemas/SortOrder'
          - description: Indicates how to sort the returned data based on game server registration timestamp. Use <code>ASCENDING</code> to retrieve oldest game servers first, or use <code>DESCENDING</code> to retrieve newest game servers first. If this parameter is left empty, game servers are returned in no particular order.
        Limit:
          allOf:
          - $ref: '#/components/schemas/PositiveInteger'
          - description: The maximum number of results to return. Use this parameter with <code>NextToken</code> to get results as a set of sequential pages.
        NextToken:
          allOf:
          - $ref: '#/components/schemas/NonZeroAndMaxString'
          - description: A token that indicates the start of the next sequential page of results. Use the token that is returned with a previous call to this operation. To start at the beginning of the result set, do not specify a value.
    GameServerData:
      type: string
      pattern: .*\S.*
      minLength: 1
      maxLength: 1024
    UnauthorizedException: {}
    Timestamp:
      type: string
      format: date-time
    PositiveInteger:
      type: integer
      minimum: 1
    GameServerUtilizationStatus:
      type: string
      enum:
      - AVAILABLE
      - UTILIZED
    GameServers:
      type: array
      items:
        $ref: '#/components/schemas/GameServer'
    GameServerConnectionInfo:
      type: string
      pattern: .*\S.*
      minLength: 1
      maxLength: 512
    SortOrder:
      type: string
      enum:
      - ASCENDING
      - DESCENDING
  parameters:
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/gamelift/
x-hasEquivalentPaths: true
