openapi: 3.2.0
info:
  version: 2015-10-01
  x-release: v4
  title: 'Amazon GameLift #X Amz Target=GameLift.DeleteFleet API'
  description: Amazon GameLift provides solutions for hosting session-based multiplayer game servers in the cloud, including tools for deploying, operating, and scaling game servers.
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: gamelift
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/gamelift-2015-10-01.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://gamelift.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon GameLift multi-region endpoint
- url: https://gamelift.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Amazon GameLift multi-region endpoint
- url: http://gamelift.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon GameLift endpoint for China (Beijing) and China (Ningxia)
- url: https://gamelift.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Amazon GameLift endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: '#X Amz Target=GameLift.DeleteFleet'
paths:
  /#X-Amz-Target=GameLift.DeleteFleet:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    post:
      operationId: DeleteFleet
      description: 'Deletes all resources and information related a fleet. Any current fleet instances, including those in remote locations, are shut down. You don''t need to call DeleteFleetLocations separately.


        If the fleet being deleted has a VPC peering connection, you first need to get a valid authorization (good for 24 hours) by calling CreateVpcPeeringAuthorization. You do not need to explicitly delete the VPC peering connection.


        To delete a fleet, specify the fleet ID to be terminated. During the deletion process the fleet status is changed to DELETING. When completed, the status switches to TERMINATED and the fleet event FLEET_DELETED is sent.


        Learn more


        Setting up Amazon GameLift Fleets'
      responses:
        '200':
          description: Success
        '480':
          description: NotFoundException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundException'
              examples:
                DeleteFleet480Example:
                  summary: Default DeleteFleet 480 response
                  x-microcks-default: true
                  value: example-value
        '481':
          description: InternalServiceException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServiceException'
              examples:
                DeleteFleet481Example:
                  summary: Default DeleteFleet 481 response
                  x-microcks-default: true
                  value: example-value
        '482':
          description: InvalidFleetStatusException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidFleetStatusException'
              examples:
                DeleteFleet482Example:
                  summary: Default DeleteFleet 482 response
                  x-microcks-default: true
                  value: example-value
        '483':
          description: UnauthorizedException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnauthorizedException'
              examples:
                DeleteFleet483Example:
                  summary: Default DeleteFleet 483 response
                  x-microcks-default: true
                  value: example-value
        '484':
          description: InvalidRequestException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidRequestException'
              examples:
                DeleteFleet484Example:
                  summary: Default DeleteFleet 484 response
                  x-microcks-default: true
                  value: example-value
        '485':
          description: TaggingFailedException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaggingFailedException'
              examples:
                DeleteFleet485Example:
                  summary: Default DeleteFleet 485 response
                  x-microcks-default: true
                  value: example-value
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeleteFleetInput'
      parameters:
      - name: X-Amz-Target
        in: header
        required: true
        schema:
          type: string
          enum:
          - GameLift.DeleteFleet
      summary: Amazon GameLift Delete Fleet
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - '#X Amz Target=GameLift.DeleteFleet'
components:
  parameters:
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
  schemas:
    DeleteFleetInput:
      type: object
      required:
      - FleetId
      title: DeleteFleetInput
      properties:
        FleetId:
          allOf:
          - $ref: '#/components/schemas/FleetIdOrArn'
          - description: A unique identifier for the fleet to be deleted. You can use either the fleet ID or ARN value.
    InvalidFleetStatusException: {}
    NotFoundException: {}
    InvalidRequestException: {}
    UnauthorizedException: {}
    FleetIdOrArn:
      type: string
      pattern: ^fleet-\S+|^arn:.*:fleet\/fleet-\S+
    TaggingFailedException: {}
    InternalServiceException: {}
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/gamelift/
x-hasEquivalentPaths: true
